run:
  timeout: 5m
linters:
  enable:
    - bodyclose
    - dogsled
    - dupl
    - durationcheck
    - exportloopref
    - exhaustive
    - gochecknoinits
    - goconst
    - gocritic
    - gofmt
    - goimports
    - gomnd
    - gosec
    - govet
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - stylecheck
    - unconvert
    - unparam
linters-settings:
  goconst:
    # Exclude few word constants
    min-len: 20
    # Don't use goconst to check test files
    ignore-tests: true
  lll:
    line-length: 140
issues:
  exclude-rules:
    # Excluding single digits from magic number detector because it produces too many obvious results (like klog)
    - text: "Magic number: [0-9]{1},"
      linters:
        - gomnd
    # Exclude tests from long line linter
    - linters:
        - lll
      path: _test\.go
    # Exclude tests from duplicate linter
    - linters:
        - dupl
      path: _test\.go
  # always show all issues rather than only showing 50 at a time
  max-issues-per-linter: 0
  # always show all issues of a type rather than showing 3
  max-same-issues: 0
output:
  print-issued-lines: true
  print-linter-name: true
